#============== milvus 配置部分 =================
milvus:
  host: '127.0.0.1'
  port: '19530'
  collection_name: 'base_patch32_add'
  vector_dim: 512
  topk: 10

  index_params: # 索引参数
    'metric_type': 'IP'  # 内积距离
    'index_type': 'HNSW' # 算法类型
    'params':
      "M": 8
      "efConstruction": 128

  search_params:
    "metric_type": 'IP'
    "params":
      "ef": 20 # topk < search_param的ef

#============= Gradio模型配置部分 ================
gradio:
  checkpoint_dir: 'openai/clip-vit-base-patch32' # gradio模型需与用来embeds存入milvus的模型一致

#================ 微调配置部分 ==================
finetune:
  checkpoint_dir: 'openai/clip-vit-base-patch32' # 可以是huggingface上的模型名称或本地文件夹
  save_dir: './checkpoint'

#================ onnx 配置部分 ================
onnx:
  checkpoint_dir: 'openai/clip-vit-base-patch32' # 可以是huggingface上的模型名称或本地文件夹
  save_dir: './onnx'
